# Generated by Django 5.2.4 on 2025-07-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-19T00:00:00Z'),
            preserve_default=False,
        ),
    ]
